### ISSUE TITLE
Loading previous chart gives an error

### ISSUE THREAD

**Issue by mhkeller** [Quartz/Chartbuilder#177]
The button is available but when clicked it throws `r.model` is null. When I inspect local storage that's also `null`. I'm in FF 39.0 but @joannaskao said she saw something similar in the Chrome 43.0.2357132

![screen shot 2015-07-10 at 1 03 57 pm](https://cloud.githubusercontent.com/assets/498744/8624198/440802c2-2704-11e5-8bd9-9bd7c4835c31.png)

**Comment by nsonnad** [comment]
This is because you have no chart loaded into local storage. Once the timer runs out and you start editing, it will be saved on any change and the button will work.

But the button shouldn't appear if there's nothing in local storage, so I've got a PR for that. https://github.com/Quartz/Chartbuilder/pull/181

**Comment by nsonnad** [comment]
Fixed at fef27005133a8c36a6386197e78115831f7da08e
