### ISSUE TITLE
Allow support for parsing timestamps in date column

### ISSUE THREAD

**Issue by edmundtadros** [Quartz/Chartbuilder#186]
Chartbuilder 2.0 is awesome. Thanks.

Is there a way to make the sugar parser look for "Timestamp" as well as "Date"?

I looked around and it isn't specified anywhere in your code. I assume is some auto Sugar.js function?

**Comment by nsonnad** [comment]
Hey edmund, the line you are looking for is part of the `parse-data-by-series` function, which splits the data JSON into separate objects for each column and thus also checks whether the first column is a date. It currently checks for the regex `/date|time/year/i`, but you could certainly ad whatever you want to that. See here:

https://github.com/Quartz/Chartbuilder/blob/master/src/js/util/parse-data-by-series.js#L8

**Comment by nsonnad** [comment]
Sorry had to delete my incorrect comment. Was thinking "hey we should refactor this" but turns out, we already had. There is a `parse-utils` object that has what you're looking for. You can modify the `datePattern` defined at the top.

https://github.com/Quartz/Chartbuilder/blob/master/src/js/util/parse-utils.js

FYI: It gets called by the [input parser](https://github.com/Quartz/Chartbuilder/blob/dadc6f99649b10927b961d2d255b36033d05f8b4/src/js/util/parse-delimited-input.js) and there are also a [few tests for it](https://github.com/Quartz/Chartbuilder/blob/dadc6f99649b10927b961d2d255b36033d05f8b4/test/parse-input.js#L23-L31)

**Comment by edmundtadros** [comment]
Great. I'll check it out.

**Comment by nsonnad** [comment]
I may have misunderstood your question. Are you trying to get it to recognize the text `timestamp` or recognize timestamps? Sugar should be able to parse your timestamps just fine, see [the docs](http://sugarjs.com/date_formats). You will have to make sure to convert it to a number first, though.

**Comment by edmundtadros** [comment]
Sorry, yes. I wanted it to recognise a column named "Timestamp". It already recognises data that is of the usual timestamps we use here.

**Comment by yanofsky** [comment]
If I understand properly, you'll want to change this line https://github.com/Quartz/Chartbuilder/blob/master/src/js/util/parse-utils.js#L2

from `var datePattern = /^(date|time|year)$/i;` to `var datePattern = /^(date|time|year|timestamp)$/i;`

**Comment by edmundtadros** [comment]
Works a treat. Thanks.
