### ISSUE TITLE
Can't get .styl files open

### ISSUE THREAD

**Issue by khantasha** [Quartz/Chartbuilder#234]
I installed stylus using npm, but I try to open the file and get this message:

"No application knows how to open /Users/akanik/Downloads/Chartbuilder-master/src/styl/colors.styl."

Help! Thanks.

**Comment by yanofsky** [comment]
You're double clicking those in Finder/Window's explorer? 

They're just text files, so you'll need to have to follow the process here for windows
http://windows.microsoft.com/en-us/windows/change-file-open-program#1TC=windows-7
or here for OS X
http://www.dummies.com/how-to/content/how-to-assign-a-file-type-to-an-application-in-mac.html

so that .styl files are associated with your text editor.

**Comment by yanofsky** [comment]
@khantasha did that work?

**Comment by khantasha** [comment]
Hi! Yes! That worked! Thank you!
