### ISSUE TITLE
Cloud Typography does not export

### ISSUE THREAD

**Issue by lseemann** [Quartz/Chartbuilder#253]
Just upgraded to the latest version of Chartbuilder. Wow. Thank you for your incredible work.

We use Hoeffler's Cloud Typography and although the typefaces show up in the visual renderer, the fallback typefaces get rendered in the exported images. [Here is our instance](http://chicagomag.com/utilities/chartbuilder/).

This was not the case when we were still on [Chartbuilder v1](http://chicagomag.com/utilities/chartbuilder-v1/).

Any suggestions?

**Comment by yanofsky** [comment]
Hi @lseemann,

This has been a symptom of a couple of issues that as far as I can tell all have solutions. Checkout out #163. 

My first thought is that you're running into a cross-domain issue since you're loading your fonts from media.chicagomag.com but your instance lives on chicagomag.com. Could you move that css file into your chartbuilder project?

**Comment by lseemann** [comment]
That’s exactly it. Thanks for the quick reply, David!

**Comment by yanofsky** [comment]
📈
